irq-imx-irqsteer: Fixed compile issues when CONFIG_PM_SLEEP is not set
Freescale/linux-fslc pull request #165
Opened 2020-11-05 13:34 UTC by MDoswaldSchiller

- Fixed a compile error in imx_irqsteer_chans_enable where the type name was used instead of the variable name
- Guard the SET_RUNTIME_PM_OPS macro with a check for CONFIG_PM_SLEEP

2020-11-05 13:50 UTC, otavio approved these changes
@zandrey could you take a look at this as well?

2020-11-05 14:00 UTC, zandrey requested changes
@MDoswaldSchiller 

This commit is missing `Signed-off-by:` tag and (possibly) `Fixes:` tag.

Later one is more interesting for me to understand which merge commit broke it.

2020-11-05 14:50 UTC, MDoswaldSchiller commented
I've added the requested info to the commit message. Was this the correct way to do it? (Still learning the git basics)

2020-11-05 16:00 UTC, zandrey commented
> 
> 
> I've added the requested info to the commit message.

Yeap, that is now correct - thanks for updating it!

> Was this the correct way to do it? (Still learning the git basics)

Maybe also for the future: if you keep the commit header at 50 chars and body at ~70 - that would help with readability.
For kernel commits - you can follow the guidelines from the kernel documentation section on [Submitting patches](https://www.kernel.org/doc/html/v5.4/process/submitting-patches.html)

_Back to the patch_:
There is a slight discrepancy here though: I saw that Andy suggested you to remove `CONFIG_PM_SLEEP` from the driver [here](https://github.com/Freescale/linux-fslc/commit/1b98a5088798abe3786a3c35f1f66115aef37883#r43091321) but your commit does the opposite - it disables `SET_RUNTIME_PM_OPS` when `CONFIG_PM_SLEEP` is defined, effectively introducing one additional usage of that config variable.

Is there any reason you didn't follow the advise of Andy? I guess the proposal is good and it should be addressed further.

-- andrey

2020-11-05 16:10 UTC, MDoswaldSchiller commented
> _Back to the patch_:
> There is a slight discrepancy here though: I saw that Andy suggested you to remove `CONFIG_PM_SLEEP` from the driver [here](https://github.com/Freescale/linux-fslc/commit/1b98a5088798abe3786a3c35f1f66115aef37883#r43091321) but your commit does the opposite - it disables `SET_RUNTIME_PM_OPS` when `CONFIG_PM_SLEEP` is defined, effectively introducing one additional usage of that config variable.
> 
> Is there any reason you didn't follow the advise of Andy? I guess the proposal is good and it should be addressed further.

Yes, I did read the suggestion from Andy. I was under the impression that the APIs marked with __maybe_unused are also included in the final binary therefore I thought that it may be better to use the CONFIG_PM_SLEEP macro to exclude the API from compilation. 

I am no kernel expert so if the __maybe_unused is the correct way to go I am happy to change my patch to the suggested fix.

2020-11-05 16:36 UTC, zandrey commented
> 
> 
> > _Back to the patch_:
> > There is a slight discrepancy here though: I saw that Andy suggested you to remove `CONFIG_PM_SLEEP` from the driver [here](https://github.com/Freescale/linux-fslc/commit/1b98a5088798abe3786a3c35f1f66115aef37883#r43091321) but your commit does the opposite - it disables `SET_RUNTIME_PM_OPS` when `CONFIG_PM_SLEEP` is defined, effectively introducing one additional usage of that config variable.
> > Is there any reason you didn't follow the advise of Andy? I guess the proposal is good and it should be addressed further.
> 
> Yes, I did read the suggestion from Andy. I was under the impression that the APIs marked with __maybe_unused are also included in the final binary therefore I thought that it may be better to use the CONFIG_PM_SLEEP macro to exclude the API from compilation.

They may or may not be included, depending on the reference. Commit 0d7ebbbc6eaa5539f78ab20ed6ff1725a4e332ef gives some details on the definition of this macro, and [Kernel docs on coding style](https://github.com/Freescale/linux-fslc/blob/5.4-2.1.x-imx/Documentation/process/coding-style.rst#21-conditional-compilation) details on the usage. I believe it is OK to go ahead with Andy's suggestion.

> 
> I am no kernel expert so if the __maybe_unused is the correct way to go I am happy to change my patch to the suggested fix.

Please do!

-- andrey

2020-11-06 08:11 UTC, MDoswaldSchiller commented
I've changed the patch to go with Andy's suggestion. Is this correct now?

2020-11-06 10:07 UTC, zandrey approved these changes
`Acked-by: Andrey Zhizhikin <andrey.zhizhikin@leica-geosystems.com>`

2020-11-06 11:26 UTC, otavio approved these changes

2020-11-06 11:26 UTC, merged

2020-11-06 17:33 UTC, zandrey commented
@otavio I'll do a cherry-pick of this into `2.2.x` kernel and combine it with `v5.4.75` update for all branches.

2020-11-06 17:55 UTC, otavio commented
Awesome; thanks for all your help @zandrey

2020-11-09 09:32 UTC, MDoswaldSchiller commented
@zandrey: Thank you for your help and guidance to get this merged

2020-11-09 10:18 UTC, zandrey commented
@MDoswaldSchiller No problem! I've also cherry-picked it to `5.4.-2.2.x-imx` branch as well in PR #166 , so we have it in all NXP kernel versions.

I would bring the kernel recipe update today so you can then pull the latest kernel version with your patch included from the layer.

-- andrey